"""empty message

Revision ID: 2480af7416e2
Revises: 1ae5693f2b94
Create Date: 2020-04-21 16:42:55.585653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2480af7416e2'
down_revision = '1ae5693f2b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expertise_area', table_name='expertise')
    op.create_index(op.f('ix_expertise_area'), 'expertise', ['area'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expertise_area'), table_name='expertise')
    op.create_index('ix_expertise_area', 'expertise', ['area'], unique=1)
    # ### end Alembic commands ###
