"""empty message

Revision ID: 35a8d6c252c1
Revises: 5ca81659c974
Create Date: 2020-04-26 21:28:57.765055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a8d6c252c1'
down_revision = '5ca81659c974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('email', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'email')
    # ### end Alembic commands ###
