"""empty message

Revision ID: 45b99977c9f0
Revises: 81df366c3751
Create Date: 2020-04-02 16:12:40.884466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b99977c9f0'
down_revision = '81df366c3751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netid', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_netid'), 'users', ['netid'], unique=True)
    op.create_index(op.f('ix_users_timestamp'), 'users', ['timestamp'], unique=False)
    op.create_table('photographers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photographer_netid', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['photographer_netid'], ['users.netid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photographers_description'), 'photographers', ['description'], unique=False)
    op.create_index(op.f('ix_photographers_email'), 'photographers', ['email'], unique=True)
    op.create_index(op.f('ix_photographers_first_name'), 'photographers', ['first_name'], unique=False)
    op.create_index(op.f('ix_photographers_last_name'), 'photographers', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photographers_last_name'), table_name='photographers')
    op.drop_index(op.f('ix_photographers_first_name'), table_name='photographers')
    op.drop_index(op.f('ix_photographers_email'), table_name='photographers')
    op.drop_index(op.f('ix_photographers_description'), table_name='photographers')
    op.drop_table('photographers')
    op.drop_index(op.f('ix_users_timestamp'), table_name='users')
    op.drop_index(op.f('ix_users_netid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
