"""empty message

Revision ID: bd6e7cae30b0
Revises: 685e2b0eb013
Create Date: 2020-04-30 19:08:19.034285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6e7cae30b0'
down_revision = '685e2b0eb013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photographers', sa.Column('notif_checkbox', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_photographers_notif_checkbox'), 'photographers', ['notif_checkbox'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photographers_notif_checkbox'), table_name='photographers')
    op.drop_column('photographers', 'notif_checkbox')
    # ### end Alembic commands ###
