"""empty message

Revision ID: c3ccf611bee7
Revises: b7d4c169bc61
Create Date: 2020-04-27 16:58:43.492318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ccf611bee7'
down_revision = 'b7d4c169bc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photographers', sa.Column('avg_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photographers', 'avg_rating')
    # ### end Alembic commands ###
