"""empty message

Revision ID: dbd20373a78a
Revises: f0242dd0cf74
Create Date: 2020-04-21 21:26:53.819379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd20373a78a'
down_revision = 'f0242dd0cf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_reviews_timestamp'), 'reviews', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_timestamp'), table_name='reviews')
    op.drop_column('reviews', 'timestamp')
    # ### end Alembic commands ###
