"""first migrate

Revision ID: 81df366c3751
Revises: 
Create Date: 2020-04-02 11:04:38.702354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81df366c3751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('netid', sa.String(length=80), nullable=False),
    sa.Column('photographer_netid', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('netid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
